### ISSUE TITLE
WARNING!!!

### ISSUE THREAD

**Issue by ghost** [DeathHackz/PupilPathPlus#1]
I think this userscript will stop working, because they are changing the pupilpath script because its been glitching.

**Comment by KaBankz** [comment]
Unfortunately, if it does stop working I will no longer be able to fix it because I no longer have access to my pupilpath account.

**Comment by ghost** [comment]
what if I give you mine. Like I really love and enjoy your script. and I
rly need it. Or you could teach me how. Plz, I rly love using your script!

**Comment by KaBankz** [comment]
I appreciate the effort, but I don't think it's safe to share your account with anyone besides yourself. You are free to fork this repo and work on it yourself. If you want to learn how to code this script, I recommend you google javascript tutorials and start learning from the basics.

**Comment by ghost** [comment]
alright. Thanks I will

**Comment by ghost** [comment]
But what i dont understand is how to make the script so that it changes
something on the website. The javascript tutorials dont teach that, its
mostly useless things.

**Comment by KaBankz** [comment]
To change something on a website requires you to manipulate the DOM with javascript. If you go to youtube and watch some videos on DOM manipulation with javascript you should be set.

**Comment by ghost** [comment]
thank you very much, I appreciate it!

**Comment by ghost** [comment]
Have you ever thought of hacking pupilpath from the inside not just the
outside?

**Comment by KaBankz** [comment]
Hacking pupilpath from the inside would be more difficult than necessary and illegal. Just bring your grades up instead of becoming a criminal. This userscript is for those times when you just want to flex better grades or just calculate an average.

**Comment by ghost** [comment]
no, no, thats not what i meant. I meant editing the grades on the inside,
like if you tap on the grade. That way you can flex your grades both ways,
but totally legally.

**Comment by KaBankz** [comment]
Opps, my bad for the misinterpretation. But yeah that is possible, but I never tried it, for that I'd assume all you would have to do is change the element the grade is in to be a input. You can try that out and see what you like more.

**Comment by ghost** [comment]
ok, but i have a question. If you make an inspect elemnt change, how would you save it, so that everytime you open that certain website it runs automatically just like it would with tampermonkey.

**Comment by KaBankz** [comment]
I don't think something like that is possible, I may be wrong, but google it just to make sure.

**Comment by ghost** [comment]
i did. There were many weird and complicated ways such as using
get.ElementById, and ClassName, and all that. My idea is to add on to your
code and make it so that it can  edit grades on the inside. Im trying to
make it so that everytime you press on the grade from the inside, a box
like the one you made would pop up. So my idea was to make an inspect
element change, try to save it, and make it run that edit everytime the
website is being used.

**Comment by KaBankz** [comment]
So for what you want all you would have to do is add a event listener to the element the grade is in, and make it open the grade changer popup. No need for inspect element.

**Comment by ghost** [comment]
Yeah but everytime i try to do that, it either gives me to many Ids, or says undefined. And By the way, I started a public gist. Its basically your code and me trying to add stuff to it.

**Comment by KaBankz** [comment]
Yes you should get back a bunch of id's, each one represents a grade for each class. I recommend you use querySelectorAll to get all the elements with a grade in it, then loop over them with forEach, and add an event listener to each element to open the grade changer popup.

**Comment by ghost** [comment]
ok, i will see if i can do that and i will tell u

**Comment by ghost** [comment]
what if you cant find an id for something. For example it says : <span style="color: #0087FF" data-gtype="Honors"> for a certain thing. It doesn't say 100, which is the etxt im trying to edit.

**Comment by KaBankz** [comment]
If there is no class or ID, then you will have to select it from child nodes or parent nodes. You should learn more about the DOM, this entire userscript relies on modifying the DOM so you need to have an understanding on how to select elements, change elements, add/remove elements, and updating elements. If you have any questions google them, stackoverflow is a godsend and should have an answer to all your questions. When I made this userscript I had little to no understanding of javascript and stackoverflow was all I needed to make this userscript.

**Comment by ghost** [comment]
ok thank you,!

**Comment by ghost** [comment]
hi, its been along time since ive talked to you. i have a question about
something. how do you edit what's between a <h></h>. Im working on
something to do with that but i just dont know how to edit whats
between using the console, in order for it to be a script so that i can put
it into a code/ script runner.

**Comment by KaBankz** [comment]
There is no "h" tag in HTML, so I assume you meant a header tag such as "h1". To edit what's between the tag you first have to select it by using querySelector, getElementById, or any other selector method. Then depending on what you want to change you can use innerText to change the text or innerHtml to change the HTML.

**Comment by ghost** [comment]
thx, i figured out the innerHTML, but you gave me another option, so now i
have more in my inventory.

**Comment by ghost** [comment]
I have a question about pupilpath. so im working on a code for it, and if
for example i want to change the visual for my grade in Ela, I would
put: document.getElementsByTagName("p")[3].innerHTML="Class Status: <span
id=standing style.color= #AA9901><img src=/img/ico/tick.png> 82.09 -
Borderline</span>";. so my question is how to make different codes affect
different classes?

**Comment by ghost** [comment]
also, when i put a certain code in console it runs...then when i save that
code in a script runner, and reload the page , the edit i made reverts back
to its original state, and when i open console it says "A/An TypeError
occured in your code with the following message:Cannot read property
'style' of undefined" but then i write the same code and it does the work.

**Comment by KaBankz** [comment]
The issue with the code only working in the console is probably because you are trying to run code that modifies DOM elements that have not yet been rendered. It works in the console because the page has finished rendering when you run the code, but for userscripts you have to specify the run time or it will try to run code before the page has finished loading. Here is a reference to help you understand it better: [https://www.tampermonkey.net/documentation.php#_run_at](https://www.tampermonkey.net/documentation.php#_run_at) For your case you should use:
```javascript
// @run-at    document-end
```
---
When you do this:
```javascript
document.getElementsByTagName("p")[3].innerHTML="Class Status: <span id=standing style.color= #AA9901><img src=/img/ico/tick.png> 82.09 - Borderline</span>";
```
You are selecting all the `p` tags, then using an index (3 in this case) to select a single one. This is not what you should do. That will select all `p` tags even ones that do not contain grades. I recommend that you find an element that wraps all the grade elements. In my original code, I have this:
```javascript
document.querySelectorAll("table#progress-card > tbody > tr > td > span");
```
This code selects only grades because I selected the `span` element that contained all the grades elements. With this, you can just loop through the grades like so :
```javascript
const gradeParent = document.querySelectorAll('table#progress-card > tbody > tr > td > span');
gradeParent.forEach(e => {
  const originalGrade = parseFloat(e.innerText);
  const className = e.parentElement.parentElement.parentElement.childNodes[1].innerText.toUpperCase();
  console.log(`${className} = ${originalGrade}`);
  switch (className) {
    case 'ELA':
      e.innerHTML = `Class Status: <span id="standing" style="color:#AA9901";><img src="/img/ico/tick.png" /> 82.09 - Borderline</span>`;
      break;
    case 'MATH':
      e.innerHTML = `Class Status: <span id="standing" style="color:#AA9901";><img src="/img/ico/star.png" /> 90 - Passing</span>`;
      break;
  }
  // Whatever else you need...
});
```
But as you mentioned before PupilPath changed their website, so these selectors might not work, you will have to modify it to fit your use case. If you have trouble using selectors, then you should do some google searches, I personally learned how to use selectors by watching videos on youtube on web scraping.

**Comment by ghost** [comment]
Thx you so much, i rly appreciate the assistance that u give me.
